name: Inflation Pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Skip pipelines in CD
        run: |
          echo "Pipelines não são executados no CD."
          echo "Somente build e exportação de artefatos."

      - name: Upload raw data
        uses: actions/upload-artifact@v4
        with:
          name: raw-data
          path: data/raw/*
          if-no-files-found: ignore

      - name: Upload processed data
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: data/processed/*
          if-no-files-found: ignore

      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: data/output/*
          if-no-files-found: ignore
